apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkin-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkin-system
  template:
    metadata:
      labels:
        app: checkin-system
    spec:
      containers:
      - name: checkin-system
        image: ygyunge/checkin-system
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: checkin-secrets
--- 
apiVersion: v1
kind: Service
metadata:
  name: checkin-system-service
spec:
  type: LoadBalancer
  selector:
    app: checkin-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 